const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1080}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http**/*',r=>r.abort());
 await page.goto('file://'+path.join(__dirname,'index.html'));
 await page.locator('[data-node="nand"]').waitFor();
 assert.equal(await page.evaluate(()=>location.search),'?tab=supply-chain');
 assert.equal(await page.locator('[data-node]').count(),17);
 assert((await page.locator('[data-node="ai_services"]').textContent()).includes('OpenAI'));
 assert((await page.locator('[data-node="ai_services"]').textContent()).includes('Anthropic／Claude'));
 assert((await page.locator('[data-node="device"]').textContent()).includes('Apple'));
 assert((await page.locator('[data-node="server"]').textContent()).includes('NEC'));
 await page.click('[data-node="server"]');
 const serverDetail=await page.locator('#layer-detail').textContent();
 for(const name of ['Dell','HPE','Supermicro','Lenovo','NVIDIA','Quanta','Wiwynn','Hon Hai'])assert(serverDetail.includes(name),name);
 assert(serverDetail.includes('ブランド'));
 assert(serverDetail.includes('ODM'));
 await page.click('[data-node="ai_services"]');assert((await page.locator('#layer-detail').textContent()).includes('非上場'));assert((await page.locator('#layer-detail').textContent()).includes('クラウド計算能力'));
 await page.click('[data-node="device"]');assert((await page.locator('#layer-detail').textContent()).includes('20.4%'));assert((await page.locator('#layer-detail').textContent()).includes('NAND・組み込みストレージ'));
 await page.click('[data-node="nand"]');
 assert((await page.locator('#layer-detail').textContent()).includes('買い手：企業向けSSD'));
 assert((await page.locator('#layer-detail').textContent()).includes('買い手：スマホ・PCメーカー'));
 await page.click('[data-node="ssd"]');
 assert((await page.locator('#layer-detail').textContent()).includes('仕入先：NANDフラッシュ'));
 assert((await page.locator('#layer-detail').textContent()).includes('SSDは完成品、NANDは内部の記録媒体'));
 await page.click('[data-node="nand"]');
 await page.screenshot({path:path.join(__dirname,'qa/map-desktop.png'),fullPage:true});
 await page.click('#tab-guide');
 assert.equal(await page.evaluate(()=>location.search),'?tab=ai-functions');
 assert(await page.locator('#panel-guide').isVisible());
 assert.equal(await page.locator('[data-guide-group]').count(),3);
 assert((await page.locator('#panel-guide').textContent()).includes('SSDは完成品'));
 assert((await page.locator('#panel-guide').textContent()).includes('超高速転送'));
 assert((await page.locator('#panel-guide').textContent()).includes('SSDへ戻す'));
 assert.equal(await page.locator('.memory-detail').count(),3);
 assert((await page.locator('.memory-detail.nand').textContent()).includes('ベクトルDB'));
 assert((await page.locator('.memory-detail.nand').textContent()).includes('キオクシア'));
 await page.screenshot({path:path.join(__dirname,'qa/guide-desktop.png'),fullPage:true});
 await page.locator('section[aria-labelledby="data-flow-title"]').screenshot({path:path.join(__dirname,'qa/guide-flow.png')});
 await page.click('[data-guide-group="hbm"]');
 assert.equal(await page.locator('#tab-chart').getAttribute('aria-selected'),'true');
 assert.equal(await page.evaluate(()=>location.search),'?tab=stock-comparison');
 assert.equal(await page.locator('#group').inputValue(),'hbm');
 await page.click('#tab-map');
 await page.click('[data-node="nand"]');
 await page.click('#compare-layer');
 await page.waitForFunction(()=>window.DASHBOARD_TEST.getState().chart?.width>0);
 assert.equal(await page.locator('[data-chain]').count(),17);
 await page.click('[data-chain="hbm"]');
 assert.equal(await page.locator('#group').inputValue(),'hbm');
 assert.equal(await page.locator('[data-chain="hbm"]').getAttribute('aria-pressed'),'true');
 assert.equal((await page.evaluate(()=>DASHBOARD_TEST.getState().selected)).length,3);
 await page.click('[data-chain="ssd"]');
 assert.equal(await page.locator('#group').inputValue(),'ssd');
 assert.deepEqual(await page.evaluate(()=>DASHBOARD_TEST.getState().selected),['285A.T','SNDK']);
 await page.click('[data-chain="nand"]');
 const start=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState(),base=Date.parse(s.comparison.baseDate+'T00:00:00Z');return {first:s.comparison.first,baseDate:s.comparison.baseDate,last:s.comparison.last,values:s.chart.data.datasets.map(d=>d.data.find(v=>v.x===base)?.y),names:s.selected,range:s.comparison.series.map(s=>s.change)}});
 assert.deepEqual(start.names,['285A.T','SNDK']);assert.equal(start.first,'2026-01-02');assert.equal(start.baseDate,'2026-01-05');assert.equal(start.last,'2026-09-04');assert.deepEqual(start.values,[100,100]);
 assert.equal(await page.locator('[data-metric]').count(),5);assert((await page.locator('.metric-flow').textContent()).includes('TTM EPS'));assert((await page.locator('.metric-flow').textContent()).includes('予想PER'));
 const fundamentals=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState();return {peLabels:s.peChart.data.datasets.map(d=>d.label),peValues:s.peChart.data.datasets.flatMap(d=>d.data.map(p=>p.y)),peScale:s.peChart.scales.y.type,epsValues:s.epsCharts.map(c=>c.data.datasets[0].data.map(p=>p.y)),epsCount:s.epsCharts.length,peNote:document.querySelector('#pe-note').textContent,epsTitle:document.querySelector('#eps-title').textContent}});
 assert.deepEqual(fundamentals.peLabels,['キオクシアHD','Sandisk']);assert.equal(fundamentals.peScale,'logarithmic');assert(fundamentals.peValues.every(v=>v>0));assert.equal(fundamentals.epsCount,2);assert(fundamentals.epsValues.flat().includes(1009.15));assert(fundamentals.epsValues.flat().includes(73.76));assert(fundamentals.peNote.includes('TTM EPS'));assert.equal(fundamentals.epsTitle,'TTM EPSの推移');
 await page.selectOption('#pe-kind','forward');assert.equal(await page.locator('#pe-title').textContent(),'予想PERの推移');assert.equal((await page.evaluate(()=>DASHBOARD_TEST.getState().peChart.data.datasets.length)),2);
 await page.click('[data-metric="quarterly"]');assert.equal(await page.locator('#eps-kind').inputValue(),'quarterly');assert.equal(await page.locator('#eps-title').textContent(),'四半期EPSの推移');assert((await page.evaluate(()=>DASHBOARD_TEST.getState().epsCharts.every(c=>c.config.type==='bar'))));
 await page.selectOption('#pe-kind','actual');await page.selectOption('#eps-kind','ttm');
 await page.screenshot({path:path.join(__dirname,'qa/chart-index-desktop.png'),fullPage:true});
 await page.selectOption('#mode','dual');
 let axes=await page.evaluate(()=>Object.keys(DASHBOARD_TEST.getState().chart.scales));assert(axes.includes('y0')&&axes.includes('y1'));
 await page.screenshot({path:path.join(__dirname,'qa/chart-dual-desktop.png'),fullPage:true});
 await page.locator('#choices input[value="MU"]').check();assert(await page.locator('#chart-empty').isVisible());
 await page.selectOption('#mode','index');assert(await page.locator('#price-chart').isVisible());
 const groups=await page.locator('#group option').evaluateAll(os=>os.map(o=>o.value));
 for(const g of groups){await page.selectOption('#group',g);const check=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState(),base=Date.parse(s.comparison.baseDate+'T00:00:00Z');return {error:s.comparison.error,base:s.chart.data.datasets.map(d=>d.data.find(v=>v.x===base)?.y),width:s.chart.width}});assert(!check.error,g);assert(check.width>0,g);for(const b of check.base)assert(Math.abs(b-100)<1e-8,g);}
 await page.selectOption('#group','server');await page.click('[data-period="1y"]');
 const serverFund=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState();return {eps:s.epsCharts.length,pe:s.peChart.data.datasets.length,actual:s.peChart.data.datasets.flatMap(d=>d.data.map(p=>p.y))}});assert.equal(serverFund.eps,10);assert.equal(serverFund.pe,10);assert(serverFund.actual.some(v=>Math.abs(v-100)>1));
 await page.selectOption('#pe-kind','forward');const forwardServer=await page.evaluate(()=>({count:DASHBOARD_TEST.getState().peChart.data.datasets.length,note:document.querySelector('#pe-note').textContent}));assert.equal(forwardServer.count,6);assert(forwardServer.note.includes('期間内に履歴なし'));await page.selectOption('#pe-kind','actual');
 await page.locator('.fundamental-section').screenshot({path:path.join(__dirname,'qa/fundamentals-desktop.png')});
 await page.selectOption('#group','nand');
 await page.selectOption('#basis','adjusted');
 await page.click('[data-period="3m"]');
 const calc=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState();return s.comparison.series.map(v=>({base:v.base,last:v.last,change:v.change}))});for(const v of calc)assert(Math.abs(v.change-(v.last/v.base-1)*100)<1e-8);
 await page.fill('#start','2026-09-04');await page.locator('#start').dispatchEvent('change');assert(await page.locator('#chart-empty').isVisible());
 await page.click('[data-period="ytd"]');
 const download=page.waitForEvent('download');await page.click('#download');const file=await download;await file.saveAs(path.join(__dirname,'qa/export-check.csv'));assert(fs.readFileSync(path.join(__dirname,'qa/export-check.csv'),'utf8').includes('2026-01-05'));
 for(const g of groups){
  await page.selectOption('#group',g);
  for(const period of ['5y','10y','max']){
   await page.click('[data-period="'+period+'"]');
   const state=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState(),base=Date.parse(s.comparison?.baseDate+'T00:00:00Z');return {error:s.comparison?.error,first:s.comparison?.first,baseDate:s.comparison?.baseDate,last:s.comparison?.last,bases:s.chart?.data.datasets.map(d=>d.data.find(v=>v.x===base)?.y),count:s.comparison?.dates.length}});
   assert(!state.error,g+period);assert.equal(state.last,'2026-09-04');for(const n of state.bases)assert(Math.abs(n-100)<1e-8);
   if(g==='equipment'&&period==='10y')assert(state.first<'2016-09-10');
   if(g==='equipment'&&period==='max')assert(state.first<'2001-01-01');
  }
 }
 await page.selectOption('#group','equipment');await page.click('[data-period="10y"]');
 await page.screenshot({path:path.join(__dirname,'qa/chart-10year.png'),fullPage:true});
 await page.click('[data-period="2y"]');assert.equal(await page.locator('#start').inputValue(),'2024-09-04');
 await page.click('[data-period="3y"]');assert.equal(await page.locator('#start').inputValue(),'2023-09-04');
 await page.selectOption('#group','nand');await page.click('[data-period="max"]');
 const staggered=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState();return {first:s.comparison.first,baseDate:s.comparison.baseDate,starts:Object.fromEntries(s.comparison.series.map(v=>[v.company.symbol,v.displayStart])),note:document.querySelector('#chart-note').textContent}});
 assert(staggered.starts['285A.T']<staggered.starts.SNDK);assert.equal(staggered.first,staggered.starts['285A.T']);assert.equal(staggered.baseDate,staggered.starts.SNDK);assert(staggered.note.includes('各社の線はデータが存在する日から'));
 await page.click('[data-period="1y"]');assert.equal(await page.locator('#start').inputValue(),'2025-09-04');
 const bad=await page.evaluate(()=>{const r=DASHBOARD_TEST.calculateComparison(['000660.KS'],'2000-01-01','2026-09-04','adjusted');return r.series[0].rows.every(v=>v.adjusted>0)});assert(bad);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(__dirname,'qa/chart-mobile.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');
 await page.click('#tab-guide');await page.screenshot({path:path.join(__dirname,'qa/guide-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile guide overflow');
 await page.click('#tab-map');await page.screenshot({path:path.join(__dirname,'qa/map-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile map overflow');
 await page.setViewportSize({width:320,height:800});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320 map overflow');
 await page.click('#tab-chart');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320 chart overflow');
 const direct=await browser.newPage({viewport:{width:900,height:700}});await direct.goto('file://'+path.join(__dirname,'index.html')+'?tab=ai-functions');assert(await direct.locator('#panel-guide').isVisible());assert.equal(await direct.locator('#tab-guide').getAttribute('aria-selected'),'true');await direct.click('#tab-chart');await direct.goBack();assert(await direct.locator('#panel-guide').isVisible());await direct.goto('file://'+path.join(__dirname,'index.html')+'?tab=stock-comparison');await direct.waitForFunction(()=>window.DASHBOARD_TEST.getState().chart?.width>0);assert(await direct.locator('#panel-chart').isVisible());await direct.close();
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'qa/verification.json'),JSON.stringify({result:'passed',companies:43,groups:17,initial:start,checks:['offline render','AI service and cloud demand layers','Apple device procurement path','10-company AI server and rack layer','OEM and ODM role labels','private-company labels','tab-specific query URLs','direct tab URLs and browser history','map selection','separate enterprise SSD and NAND layers','AI function guide tab','guide-to-comparison navigation','17-group picker inside price tab','picker and dropdown synchronization','common baseline with staggered history','two independent price axes','five-metric EPS to P/E explainer','quarterly annual and TTM EPS switching','actual TTM P/E overlay','forward P/E overlay','missing-history labels','EPS currency labels','invalid series count','all groups','2y 3y 5y 10y max presets','adjusted basis','date presets','invalid date interval','CSV export','390px and 320px overflow','no browser runtime errors']},null,2));
 console.log('PASS: quarterly/annual/TTM EPS and actual/forward P/E charts, 10-company AI server layer, all 17 groups, 43 listed companies, long periods, two price axes, CSV and mobile.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
