const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1080}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http**/*',r=>r.abort());
 await page.goto('file://'+path.join(__dirname,'index.html'));
 await page.locator('[data-node="nand"]').waitFor();
 assert.equal(await page.evaluate(()=>location.search),'');
 for(const id of ['map','guide','chart'])assert(await page.locator('#panel-'+id).isVisible(),'all sections on one page: '+id);
 assert.equal(await page.locator('[role=tab],[role=tabpanel]').count(),0,'no tabs inside the page: views are chosen by the dashboard shell');
 await page.waitForFunction(()=>window.DASHBOARD_TEST.getState().chart?.width>0);
 assert.equal(await page.locator('[data-node]').count(),17);
 assert((await page.locator('[data-node="ai_services"]').textContent()).includes('OpenAI'));
 assert((await page.locator('[data-node="ai_services"]').textContent()).includes('Anthropic／Claude'));
 assert((await page.locator('[data-node="device"]').textContent()).includes('Apple'));
 assert((await page.locator('[data-node="server"]').textContent()).includes('NEC'));
 await page.click('[data-node="server"]');
 const serverDetail=await page.locator('#layer-detail').textContent();
 for(const name of ['Dell','HPE','Supermicro','Lenovo','NVIDIA','Quanta','Wiwynn','Hon Hai'])assert(serverDetail.includes(name),name);
 assert(serverDetail.includes('ブランド'));
 assert(serverDetail.includes('ODM'));
 await page.click('[data-node="ai_services"]');assert((await page.locator('#layer-detail').textContent()).includes('非上場'));assert((await page.locator('#layer-detail').textContent()).includes('クラウド計算能力'));
 await page.click('[data-node="device"]');assert((await page.locator('#layer-detail').textContent()).includes('20.4%'));assert((await page.locator('#layer-detail').textContent()).includes('NAND・組み込みストレージ'));
 await page.click('[data-node="nand"]');
 assert((await page.locator('#layer-detail').textContent()).includes('買い手：企業向けSSD'));
 assert((await page.locator('#layer-detail').textContent()).includes('買い手：スマホ・PCメーカー'));
 await page.click('[data-node="ssd"]');
 assert((await page.locator('#layer-detail').textContent()).includes('仕入先：NANDフラッシュ'));
 assert((await page.locator('#layer-detail').textContent()).includes('SSDは完成品、NANDは内部の記録媒体'));
 await page.click('[data-node="nand"]');
 await page.screenshot({path:path.join(__dirname,'qa/map-desktop.png'),fullPage:true});
 await page.click('#tab-guide');
 await page.waitForFunction(()=>Math.abs(document.getElementById('panel-guide').getBoundingClientRect().top)<40);
 assert(await page.locator('#panel-map').isVisible(),'map stays on the page');
 assert.equal(await page.locator('[data-guide-group]').count(),3);
 assert((await page.locator('#panel-guide').textContent()).includes('SSDは完成品'));
 assert((await page.locator('#panel-guide').textContent()).includes('超高速転送'));
 assert((await page.locator('#panel-guide').textContent()).includes('SSDへ戻す'));
 assert.equal(await page.locator('.memory-detail').count(),3);
 assert((await page.locator('.memory-detail.nand').textContent()).includes('ベクトルDB'));
 assert((await page.locator('.memory-detail.nand').textContent()).includes('キオクシア'));
 await page.screenshot({path:path.join(__dirname,'qa/guide-desktop.png'),fullPage:true});
 await page.locator('section[aria-labelledby="data-flow-title"]').screenshot({path:path.join(__dirname,'qa/guide-flow.png')});
 await page.click('[data-guide-group="hbm"]');
 await page.waitForFunction(()=>Math.abs(document.getElementById('panel-chart').getBoundingClientRect().top)<40);
 assert.equal(await page.locator('#group').inputValue(),'hbm');
 await page.click('#tab-map');
 await page.click('[data-node="nand"]');
 await page.click('#compare-layer');
 await page.waitForFunction(()=>window.DASHBOARD_TEST.getState().chart?.width>0);
 assert.equal(await page.locator('[data-chain]').count(),17);
 await page.click('[data-chain="hbm"]');
 assert.equal(await page.locator('#group').inputValue(),'hbm');
 assert.equal(await page.locator('[data-chain="hbm"]').getAttribute('aria-pressed'),'true');
 assert.equal((await page.evaluate(()=>DASHBOARD_TEST.getState().selected)).length,3);
 await page.click('[data-chain="ssd"]');
 assert.equal(await page.locator('#group').inputValue(),'ssd');
 assert.deepEqual(await page.evaluate(()=>DASHBOARD_TEST.getState().selected),['285A.T','SNDK']);
 await page.click('[data-chain="nand"]');
 const start=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState(),base=Date.parse(s.comparison.baseDate+'T00:00:00Z');return {first:s.comparison.first,baseDate:s.comparison.baseDate,last:s.comparison.last,values:s.chart.data.datasets.map(d=>d.data.find(v=>v.x===base)?.y),names:s.selected,range:s.comparison.series.map(s=>s.change)}});
 assert.deepEqual(start.names,['285A.T','SNDK']);assert.equal(start.first,'2026-01-02');assert.equal(start.baseDate,'2026-01-05');assert.equal(start.last,'2026-10-02');assert.deepEqual(start.values,[100,100]);
 assert(!(await page.locator('#subpanel-fund').isVisible()),'EPS/PER starts hidden');
 await page.evaluate(()=>DASHBOARD_TEST.setView('fund'));assert(await page.locator('#subpanel-fund').isVisible());assert(!(await page.locator('#subpanel-price').isVisible()),'price panel hides');
 for(const id of ['#val-now','#val-decomp','#val-pe','#val-eps'])assert(await page.locator(id).isVisible(),'fund block '+id);
 assert.equal(await page.locator('[data-metric],#pe-kind,#eps-kind').count(),0,'old metric cards and selects removed');
 const fundamentals=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState(),V=DASHBOARD_TEST.valuation,k=V.companies.find(c=>c.symbol==='285A.T');return {now:s.fund.now.map(r=>({symbol:r.symbol,pe:r.pe,price:r.price,eps:r.ttm&&r.ttm.eps,status:r.status})),decomp:s.fund.decomp,preset:k.decompositionPresets.ytd,snapshotPe:k.snapshot.pe,kioxiaCell:document.querySelector('#now-body tr[data-symbol="285A.T"] [data-pe]')?.textContent,kioxiaRow:document.querySelector('#now-body tr[data-symbol="285A.T"]').textContent,sndkDecomp:document.querySelector('#decomp-body tr[data-symbol="SNDK"]').textContent,peLabels:s.peChart.data.datasets.filter(d=>!d.median).map(d=>d.label),medians:s.peChart.data.datasets.filter(d=>d.median).length,kioxiaPe:s.peChart.data.datasets.find(d=>d.label==='キオクシアHD').data.at(-1).y,peScale:s.peChart.scales.y.type,legend:document.querySelector('#pe-legend').textContent,epsCount:s.epsCharts.length,kioxiaCard:document.querySelector('.eps-card[data-symbol="285A.T"]').textContent,decompSets:s.decompChart.data.datasets.length}});
 const kx=fundamentals.now.find(r=>r.symbol==='285A.T');assert.equal(kx.price,19300);assert(Math.abs(kx.eps-833.49666667)<1e-6);assert(Math.abs(kx.pe-19300/833.49666667)<1e-9);assert(Math.abs(kx.pe-fundamentals.snapshotPe)<1e-5,'page and derive_valuation.py agree');assert.equal(fundamentals.kioxiaCell,'23.2倍');
 assert(fundamentals.kioxiaRow.includes('2026-10-30'),'confirmed Kioxia earnings date');assert(fundamentals.kioxiaRow.includes('通期の会社予想なし'));
 for(const r of fundamentals.decomp.filter(r=>r.status==='ok')){assert(Math.abs(r.lnE+r.lnPe-r.lnP)<1e-12,'log identity '+r.symbol);assert(Math.abs(r.epsContribution+r.peContribution-r.total)<1e-9,'contributions add up '+r.symbol);assert(Math.abs(r.total-r.priceChange*100)<1e-9);}
 const kd=fundamentals.decomp.find(r=>r.symbol==='285A.T');assert.equal(kd.status,'ok');assert.equal(kd.start,fundamentals.preset.startDate);assert(Math.abs(kd.lnPe-fundamentals.preset.lnPe)<1e-5&&Math.abs(kd.lnE-fundamentals.preset.lnEps)<1e-5,'page decomposition matches derive_valuation.py preset');
 assert.equal(fundamentals.decomp.find(r=>r.symbol==='SNDK').status,'unavailable');assert(fundamentals.sndkDecomp.includes('分解不可'));
 assert.deepEqual(fundamentals.peLabels,['キオクシアHD','Sandisk']);assert.equal(fundamentals.medians,2);assert.equal(fundamentals.peScale,'logarithmic');assert(Math.abs(fundamentals.kioxiaPe-23.1555)<1e-3);assert(fundamentals.legend.includes('中央値')&&fundamentals.legend.includes('10〜90%点'));
 assert.equal(fundamentals.epsCount,2);assert(fundamentals.kioxiaCard.includes('次の決算日：2026-10-30'));assert(fundamentals.kioxiaCard.includes('予想の修正（30日：上方'));assert.equal(fundamentals.decompSets,3);
 await page.click('[data-fund-period="1y"]');assert.equal(await page.locator('#start').inputValue(),'2025-10-02');assert.equal(await page.locator('[data-fund-period="1y"]').getAttribute('class'),'active');
 await page.click('[data-chain="wafer"]');const wafer=await page.evaluate(()=>Object.fromEntries([...document.querySelectorAll('#now-body tr')].map(t=>[t.dataset.symbol,t.textContent])));
 for(const sym of ['3436.T','WAF.DE'])assert(wafer[sym].includes('赤字のためPER算出不能'),sym);assert(wafer['WAF.DE'].includes('アナリスト予想：取得なし'));
 assert((await page.locator('#decomp-body tr[data-symbol="WAF.DE"]').textContent()).includes('分解不可'));assert((await page.locator('.eps-card[data-symbol="WAF.DE"]').textContent()).includes('アナリスト予想：取得なし'));assert((await page.locator('.eps-card[data-symbol="WAF.DE"]').textContent()).includes('次の決算日：未確認'));
 await page.click('[data-chain="optical"]');const liteRow=await page.locator('#now-body tr[data-symbol="LITE"]').textContent();
 assert(liteRow.includes('赤字のためPER算出不能'),'LITE loss');assert(/→ \d+(\.\d)?倍/.test(liteRow),'LITE forward P/E from analyst estimates');
 await page.click('[data-chain="hbm"]');const mu=await page.locator('#now-body tr[data-symbol="MU"]').textContent();assert(mu.includes('TTMが1四半期遅れ'),'Micron lag');assert(mu.includes('2027/08期'),'Micron relabelled fiscal years');assert((await page.locator('#now-notes').textContent()).includes('今期＝FY2027'));
 await page.locator('#subpanel-fund').screenshot({path:path.join(__dirname,'qa/fundamentals-desktop.png')});
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'390 fund overflow');await page.screenshot({path:path.join(__dirname,'qa/fundamentals-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1080});
 await page.click('[data-chain="nand"]');await page.click('[data-fund-period="ytd"]');
 await page.evaluate(()=>DASHBOARD_TEST.setView(null));assert(await page.locator('#subpanel-price').isVisible());assert(await page.locator('#tab-guide').isVisible(),'section links return on the full page');
 await page.screenshot({path:path.join(__dirname,'qa/chart-index-desktop.png'),fullPage:true});
 await page.selectOption('#mode','dual');
 let axes=await page.evaluate(()=>Object.keys(DASHBOARD_TEST.getState().chart.scales));assert(axes.includes('y0')&&axes.includes('y1'));
 await page.screenshot({path:path.join(__dirname,'qa/chart-dual-desktop.png'),fullPage:true});
 await page.locator('#choices input[value="MU"]').check();assert(await page.locator('#chart-empty').isVisible());
 await page.selectOption('#mode','index');assert(await page.locator('#price-chart').isVisible());
 const groups=await page.locator('#group option').evaluateAll(os=>os.map(o=>o.value));
 for(const g of groups){await page.selectOption('#group',g);const check=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState(),base=Date.parse(s.comparison.baseDate+'T00:00:00Z');return {error:s.comparison.error,base:s.chart.data.datasets.map(d=>d.data.find(v=>v.x===base)?.y),width:s.chart.width}});assert(!check.error,g);assert(check.width>0,g);for(const b of check.base)assert(Math.abs(b-100)<1e-8,g);}
 await page.selectOption('#group','server');await page.click('[data-period="1y"]');
 const serverFund=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState();return {eps:s.epsCharts.length,pe:s.peChart.data.datasets.filter(d=>!d.median).length,actual:s.peChart.data.datasets.flatMap(d=>d.data.map(p=>p.y)).filter(v=>v!=null),lenovo:document.querySelector('#now-body tr[data-symbol="0992.HK"]').textContent}});assert.equal(serverFund.eps,10);assert.equal(serverFund.pe,10);assert(serverFund.actual.every(v=>v>0));assert(serverFund.lenovo.includes('為替換算'),'Lenovo USD EPS converted to HKD');
 await page.evaluate(()=>DASHBOARD_TEST.setView('fund'));assert(await page.locator('#val-pe').isVisible());await page.evaluate(()=>DASHBOARD_TEST.setView(null));
 await page.selectOption('#group','nand');
 await page.selectOption('#basis','adjusted');
 await page.click('[data-period="3m"]');
 const calc=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState();return s.comparison.series.map(v=>({base:v.base,last:v.last,change:v.change}))});for(const v of calc)assert(Math.abs(v.change-(v.last/v.base-1)*100)<1e-8);
 await page.fill('#start','2026-10-02');await page.locator('#start').dispatchEvent('change');assert(await page.locator('#chart-empty').isVisible());
 await page.click('[data-period="ytd"]');
 const download=page.waitForEvent('download');await page.click('#download');const file=await download;await file.saveAs(path.join(__dirname,'qa/export-check.csv'));assert(fs.readFileSync(path.join(__dirname,'qa/export-check.csv'),'utf8').includes('2026-01-05'));
 for(const g of groups){
  await page.selectOption('#group',g);
  for(const period of ['5y','10y','max']){
   await page.click('[data-period="'+period+'"]');
   const state=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState(),base=Date.parse(s.comparison?.baseDate+'T00:00:00Z');return {error:s.comparison?.error,first:s.comparison?.first,baseDate:s.comparison?.baseDate,last:s.comparison?.last,bases:s.chart?.data.datasets.map(d=>d.data.find(v=>v.x===base)?.y),count:s.comparison?.dates.length}});
   assert(!state.error,g+period);assert(state.last>='2026-09-30'&&state.last<='2026-10-02',g+period+state.last);for(const n of state.bases)assert(Math.abs(n-100)<1e-8);
   if(g==='equipment'&&period==='10y')assert(state.first<'2016-10-10');
   if(g==='equipment'&&period==='max')assert(state.first<'2016-01-10'&&state.first>='2016-01-01');
  }
 }
 await page.selectOption('#group','equipment');await page.click('[data-period="10y"]');
 await page.screenshot({path:path.join(__dirname,'qa/chart-10year.png'),fullPage:true});
 await page.click('[data-period="2y"]');assert.equal(await page.locator('#start').inputValue(),'2024-10-02');
 await page.click('[data-period="3y"]');assert.equal(await page.locator('#start').inputValue(),'2023-10-02');
 await page.selectOption('#group','nand');await page.click('[data-period="max"]');
 const staggered=await page.evaluate(()=>{const s=DASHBOARD_TEST.getState();return {first:s.comparison.first,baseDate:s.comparison.baseDate,starts:Object.fromEntries(s.comparison.series.map(v=>[v.company.symbol,v.displayStart])),note:document.querySelector('#chart-note').textContent}});
 assert(staggered.starts['285A.T']<staggered.starts.SNDK);assert.equal(staggered.first,staggered.starts['285A.T']);assert.equal(staggered.baseDate,staggered.starts.SNDK);assert(staggered.note.includes('各社の線はデータが存在する日から'));
 await page.click('[data-period="1y"]');assert.equal(await page.locator('#start').inputValue(),'2025-10-02');
 const bad=await page.evaluate(()=>{const r=DASHBOARD_TEST.calculateComparison(['000660.KS'],'2016-01-01','2026-10-02','adjusted');return r.series[0].rows.every(v=>v.adjusted>0)});assert(bad);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(__dirname,'qa/chart-mobile.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');
 await page.click('#tab-guide');await page.screenshot({path:path.join(__dirname,'qa/guide-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile guide overflow');
 await page.click('#tab-map');await page.screenshot({path:path.join(__dirname,'qa/map-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile map overflow');
 await page.setViewportSize({width:320,height:800});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth,null,{timeout:5000}).catch(()=>{});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320 page overflow');
 await page.click('#tab-chart');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320 chart overflow');
 const viewPage=await browser.newPage({viewport:{width:900,height:700}});for(const [view,visible,hiddenOnes] of [['map','#panel-map',['#panel-guide','#panel-chart']],['guide','#panel-guide',['#panel-map','#panel-chart']],['price','#subpanel-price',['#panel-map','#panel-guide','#subpanel-fund']],['fund','#subpanel-fund',['#panel-map','#panel-guide','#subpanel-price']]]){await viewPage.goto('file://'+path.join(__dirname,'index.html')+'?view='+view);await viewPage.locator('[data-node="nand"]').waitFor({state:'attached'});assert(await viewPage.locator(visible).isVisible(),'view '+view);for(const h of hiddenOnes)assert(!(await viewPage.locator(h).isVisible()),view+' hides '+h);assert(!(await viewPage.locator('header nav').isVisible()),view+' hides section links');}await viewPage.close();
 const direct=await browser.newPage({viewport:{width:900,height:700}});await direct.goto('file://'+path.join(__dirname,'index.html')+'?tab=stock-comparison');await direct.waitForFunction(()=>window.DASHBOARD_TEST.getState().chart?.width>0);await direct.waitForFunction(()=>Math.abs(document.getElementById('panel-chart').getBoundingClientRect().top)<40);assert(await direct.locator('#panel-map').isVisible());await direct.close();
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'qa/verification.json'),JSON.stringify({result:'passed',companies:43,groups:17,initial:start,cutoff:'2026-10-02',checks:['offline render','post-split Kioxia EPS basis','AI service and cloud demand layers','Apple device procurement path','10-company AI server and rack layer','OEM and ODM role labels','private-company labels','single scrolling page (no tabs)','legacy ?tab= URLs scroll to the section','map selection','separate enterprise SSD and NAND layers','AI function guide section','guide-to-comparison navigation','17-group picker inside price section','?view= opens one section (map/guide/price/fund) for the sidebar','picker and dropdown synchronization','common baseline with staggered history','two independent price axes','priced-in table (price, TTM EPS/P/E, company and analyst forward P/E, revisions, next earnings)','Kioxia trailing P/E 23.2x = 19,300/833.50','EPS/PER log decomposition adds up to the price change','daily trailing P/E with own-history median and 10-90% band','loss-making and no-estimate labels','quarterly EPS bars with annual/forecast markers','FX-converted EPS for ASML and Lenovo','390px fund view overflow','invalid series count','all groups','2y 3y 5y 10y max presets','adjusted basis','date presets','invalid date interval','CSV export','390px and 320px overflow','no browser runtime errors']},null,2));
 console.log('PASS: priced-in table, EPS/PER decomposition, daily P/E history, EPS direction cards, 10-company AI server layer, all 17 groups, 43 listed companies, long periods, two price axes, CSV and mobile.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
